# Site settings
title: Monroe Brothers Ltd
email: your-email@domain.com
description: Monroe Brothers Ltd  provide consultancy in the field of low temperature engineering specialising in technologies using liquid nitrogen and liquid helium for industrial and scientific applications.
keywords: low temperature, engineering, liquid nitrogen, liquid helium, consultancy, industrial, scientific, applications, British Cryogenics Council
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site


website_image: "mbl_img1_large.jpg"
website_image_text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque at tellus varius sem porta sagittis tincidunt vel lectus. Pellentesque in feugiat sem, eget accumsan urna. Nulla vulputate non lectus ac porta."

bcryo_link: "http://bcryo.org.uk"
bcryo_image: "bcryo_logo.jpg"

# Build settings
markdown: kramdown
