# Site settings
title: Monroe Brothers Ltd
email: your-email@domain.com
description: Monroe Brothers Ltd provide consultancy in the field of low temperature engineering specialising in technologies using liquid nitrogen and liquid helium for industrial and scientific applications.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
