# Site settings
title: Monroe Brothers Ltd
email: your-email@domain.com
description: Monroe Brothers Ltd  provide consultancy in the field of low temperature engineering specialising in technologies using liquid nitrogen and liquid helium for industrial and scientific applications.
keywords: low temperature, engineering, liquid nitrogen, liquid helium, consultancy, industrial, scientific, applications, British Cryogenics Council
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site


main_menu:
  - Home
  - History
  - Services
  - Clients
  - Tasks
  - Contact


website_images:
  - id: "left"
    image: "mbl_hp_img1.jpg"
    text: "Tokamak Energy: The ST25 tokamak rebuilt with cryogen free TF coils to demonstrate the use of high temperature superconductors for a world record plasma duration of 29 hours."
  - id: "middle"
    image: "mbl_hp_img2.jpg"
    text: "The CLEO II magnet built by Oxford Instruments for the CESR at Cornell University."
  - id: "right"
    image: "mbl_hp_img3.jpg"
    text: "The Helial 2000 helium liquefier built by Air Liquide and installed at Diamond Light Source Ltd to cool the superconducting RF cavities."
# website_image: 
# website_image_text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque at tellus varius sem porta sagittis tincidunt vel lectus. Pellentesque in feugiat sem, eget accumsan urna. Nulla vulputate non lectus ac porta."

bcryo_link: "http://bcryo.org.uk"
bcryo_image: "bcryo_logo.jpg"

# Build settings
markdown: kramdown
